server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: 
          username: 1150681747@qq.com
          password: yz151052