server:
  port: 8019
user:
  userServiceUrl: http://localhost:8001/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true