server:
  port: 8010
user:
  userServiceUrl: http://localhost:8000/
spring:
  application:
    name: microservice-consumer-movie
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG