server:
  port: 8010
user:
  userServiceUrl: http://localhost:8000/
spring:
  application:
    name: microservice-consumer-movie
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG