server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/