server:
  port: 8087
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaozheng1998/MovieTicket/tree/master/microservice-config-server
          username: 1150681747@qq.com
          password: yz151052
encrypt:
  key: foo #设置对称密钥