server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaozheng1998/MovieTicket
          username: yaozheng1998
          password: yz151052