server:
  port: 8019
user:
  userServiceUrl: http://localhost:8001/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
logging:
  level:
    com.yz.UserFeignClient:
      DEBUG
#management:
#  security:
#    enabled: false
#将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应